/**
 * Font Awesome icon registry for sma-client
 * Maps Material Icon names to FA icon definitions for dynamic icon resolution
 */
import {
  faArrowLeft,
  faArrowRight,
  faArrowUpRightFromSquare,
  faBan,
  faBars,
  faBarsStaggered,
  faBell,
  faBolt,
  faBookmark as faBookmarkSolid,
  faBrain,
  faBriefcase,
  faBuilding,
  faCalendar,
  faCalendarDay,
  faCalendarDays,
  faCalendarXmark,
  faCamera,
  faCertificate,
  faChartPie,
  faChartSimple,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCirclePlus,
  faCircleQuestion,
  faCircleUser,
  faCircleXmark,
  faCity,
  faClipboard,
  faClipboardCheck,
  faClockRotateLeft,
  faCloudArrowUp,
  faCode,
  faCopy,
  faCreditCard,
  faDiagramProject,
  faDownload,
  faEllipsisVertical,
  faEnvelope,
  faEye,
  faEyeSlash,
  faFileArrowUp,
  faFileCirclePlus,
  faFileLines,
  faFilePdf,
  faFilter,
  faFire,
  faFolderOpen,
  faGear,
  faGift,
  faGlobe,
  faGraduationCap,
  faHandPointer,
  faImage,
  faImages,
  faInbox,
  faKey,
  faLayerGroup,
  faLightbulb,
  faLink,
  faLinkSlash,
  faList,
  faLocationDot,
  faLock,
  faMagnifyingGlass,
  faMap,
  faMedal,
  faMicrochip,
  faNewspaper,
  faPaintbrush,
  faPalette,
  faPaperclip,
  faPen,
  faPenRuler,
  faPenToSquare,
  faPeopleGroup,
  faPhone,
  faPlus,
  faQrcode,
  faRectangleList,
  faRightFromBracket,
  faRightLeft,
  faRocket,
  faRotate,
  faRotateLeft,
  faRotateRight,
  faArrowsRotate,
  faShareNodes,
  faShieldHalved,
  faSort,
  faStar,
  faStopwatch,
  faTableCells,
  faThumbsDown,
  faThumbsUp,
  faTrash,
  faTrashCan,
  faTriangleExclamation,
  faUpload,
  faUser,
  faUserGroup,
  faUserPlus,
  faUserShield,
  faUserSlash,
  faUsers,
  faWandMagicSparkles,
  faXmark,
  faBoxArchive,
  faArrowTrendUp,
  faSliders,
  faFileImage,
  faClock,
  faArrowRotateLeft,
  faChevronUp,
} from '@fortawesome/free-solid-svg-icons';

import {
  faBookmark as faBookmarkRegular,
  faClock as faClockRegular,
  faEnvelope as faEnvelopeRegular,
  faStar as faStarRegular,
  faCircleQuestion as faCircleQuestionRegular,
} from '@fortawesome/free-regular-svg-icons';

import { faCircleQuestion as faCircleQuestionFallback } from '@fortawesome/free-solid-svg-icons';

/**
 * Complete mapping from Material Icon names to Font Awesome icon definitions.
 * Used for dynamic icon resolution where icon names come from data/props.
 */
export const materialToFA = {
  // A
  account_circle: faCircleUser,
  add: faPlus,
  add_a_photo: faCamera,
  add_circle: faCirclePlus,
  add_circle_outline: faCirclePlus,
  add_photo_alternate: faFileImage,
  analytics: faChartSimple,
  apartment: faCity,
  archive: faBoxArchive,
  arrow_back: faArrowLeft,
  arrow_forward: faArrowRight,
  arrow_outward: faArrowUpRightFromSquare,
  article: faNewspaper,
  assignment: faClipboard,
  attach_file: faPaperclip,
  auto_awesome: faWandMagicSparkles,
  autorenew: faArrowsRotate,

  // B
  bar_chart: faChartSimple,
  block: faBan,
  bolt: faBolt,
  bookmark: faBookmarkSolid,
  bookmark_border: faBookmarkRegular,
  broken_image: faImage,
  brush: faPaintbrush,
  business: faBuilding,
  business_center: faBriefcase,

  // C
  calendar_month: faCalendarDays,
  calendar_today: faCalendarDay,
  call: faPhone,
  cancel: faCircleXmark,
  category: faLayerGroup,
  check: faCheck,
  check_circle: faCircleCheck,
  chevron_left: faChevronLeft,
  chevron_right: faChevronRight,
  close: faXmark,
  cloud_upload: faCloudArrowUp,
  code: faCode,
  collections: faImages,
  content_copy: faCopy,
  credit_card: faCreditCard,

  // D
  dangerous: faBan,
  delete: faTrash,
  delete_outline: faTrashCan,
  description: faFileLines,
  design_services: faPenRuler,
  dns: faDiagramProject,
  domain: faBuilding,
  download: faDownload,

  // E
  edit: faPenToSquare,
  edit_note: faPen,
  electric_bolt: faBolt,
  email: faEnvelope,
  error: faCircleExclamation,
  error_outline: faCircleExclamation,
  event: faCalendar,
  event_busy: faCalendarXmark,
  expand_less: faChevronUp,
  expand_more: faChevronDown,

  // F
  fact_check: faClipboardCheck,
  file_upload: faFileArrowUp,
  filter_list: faFilter,
  folder_open: faFolderOpen,
  format_list_bulleted: faList,

  // G
  grade: faStar,
  graphic_eq: faBarsStaggered,
  grid_view: faTableCells,
  group_add: faUserPlus,
  group_off: faUserSlash,
  groups: faPeopleGroup,

  // H
  help_outline: faCircleQuestion,
  history: faClockRotateLeft,
  hub: faDiagramProject,

  // I
  inbox: faInbox,
  info: faCircleInfo,

  // K
  keyboard_arrow_down: faChevronDown,

  // L
  lightbulb: faLightbulb,
  link: faLink,
  link_off: faLinkSlash,
  local_fire_department: faFire,
  location_on: faLocationDot,
  lock: faLock,
  logout: faRightFromBracket,

  // M
  mail: faEnvelope,
  mail_outline: faEnvelopeRegular,
  map: faMap,
  memory: faMicrochip,
  menu: faBars,
  more_vert: faEllipsisVertical,

  // N
  notifications: faBell,
  notifications_none: faBell,

  // O
  open_in_new: faArrowUpRightFromSquare,

  // P
  palette: faPalette,
  payments: faCreditCard,
  pending_actions: faClockRotateLeft,
  people: faUsers,
  people_alt: faUserGroup,
  people_outline: faUsers,
  person: faUser,
  phone: faPhone,
  picture_as_pdf: faFilePdf,
  pie_chart: faChartPie,
  place: faLocationDot,
  post_add: faFileCirclePlus,
  psychology: faBrain,
  public: faGlobe,
  publish: faUpload,

  // Q
  qr_code_scanner: faQrcode,
  quiz: faCircleQuestion,

  // R
  redeem: faGift,
  redo: faRotateRight,
  refresh: faRotate,
  replay_circle_filled: faArrowRotateLeft,
  rocket_launch: faRocket,

  // S
  schedule: faClock,
  school: faGraduationCap,
  search: faMagnifyingGlass,
  search_off: faMagnifyingGlass,
  security: faShieldHalved,
  settings: faGear,
  settings_applications: faGear,
  share: faShareNodes,
  shield_person: faUserShield,
  sort: faSort,
  star: faStar,
  star_outline: faStarRegular,
  stars: faStar,
  swap_horiz: faRightLeft,
  sync: faArrowsRotate,

  // T
  table_view: faTableCells,
  task_alt: faCircleCheck,
  text_format: faPen,
  thumb_down: faThumbsDown,
  thumb_up: faThumbsUp,
  timer: faStopwatch,
  touch_app: faHandPointer,
  trending_up: faArrowTrendUp,
  tune: faSliders,

  // U
  undo: faRotateLeft,
  upload_file: faFileArrowUp,

  // V
  verified: faCertificate,
  view_agenda: faRectangleList,
  visibility: faEye,
  visibility_off: faEyeSlash,
  vpn_key: faKey,

  // W
  warning: faTriangleExclamation,
  warning_amber: faTriangleExclamation,
  work: faBriefcase,
  work_history: faClockRotateLeft,
  work_outline: faBriefcase,
  workspace_premium: faMedal,

  // Aliases
  card_membership: faCreditCard,
  subscriptions: faBell,
  gavel: faShieldHalved,
  dashboard: faTableCells,
};

/**
 * Resolve a Material Icon name to a Font Awesome icon definition.
 * Falls back to faCircleQuestion for unknown icons.
 */
export function resolveIcon(name) {
  if (!name) return faCircleQuestionFallback;
  return materialToFA[name] || faCircleQuestionFallback;
}

// Re-export everything for convenient imports
export {
  faArrowLeft,
  faArrowRight,
  faArrowUpRightFromSquare,
  faBan,
  faBars,
  faBarsStaggered,
  faBell,
  faBolt,
  faBookmarkSolid,
  faBookmarkRegular,
  faBrain,
  faBriefcase,
  faBuilding,
  faCalendar,
  faCalendarDay,
  faCalendarDays,
  faCalendarXmark,
  faCamera,
  faCertificate,
  faChartPie,
  faChartSimple,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCirclePlus,
  faCircleQuestion,
  faCircleUser,
  faCircleXmark,
  faCity,
  faClipboard,
  faClipboardCheck,
  faClock,
  faClockRegular,
  faClockRotateLeft,
  faCloudArrowUp,
  faCode,
  faCopy,
  faCreditCard,
  faDiagramProject,
  faDownload,
  faEllipsisVertical,
  faEnvelope,
  faEnvelopeRegular,
  faEye,
  faEyeSlash,
  faFileArrowUp,
  faFileCirclePlus,
  faFileImage,
  faFileLines,
  faFilePdf,
  faFilter,
  faFire,
  faFolderOpen,
  faGear,
  faGift,
  faGlobe,
  faGraduationCap,
  faHandPointer,
  faImage,
  faImages,
  faInbox,
  faKey,
  faLayerGroup,
  faLightbulb,
  faLink,
  faLinkSlash,
  faList,
  faLocationDot,
  faLock,
  faMagnifyingGlass,
  faMap,
  faMedal,
  faMicrochip,
  faNewspaper,
  faPaintbrush,
  faPalette,
  faPaperclip,
  faPen,
  faPenRuler,
  faPenToSquare,
  faPeopleGroup,
  faPhone,
  faPlus,
  faQrcode,
  faRectangleList,
  faRightFromBracket,
  faRightLeft,
  faRocket,
  faRotate,
  faRotateLeft,
  faRotateRight,
  faArrowsRotate,
  faShareNodes,
  faShieldHalved,
  faSort,
  faStar,
  faStarRegular,
  faStopwatch,
  faTableCells,
  faThumbsDown,
  faThumbsUp,
  faTrash,
  faTrashCan,
  faTriangleExclamation,
  faUpload,
  faUser,
  faUserGroup,
  faUserPlus,
  faUserShield,
  faUserSlash,
  faUsers,
  faWandMagicSparkles,
  faXmark,
  faBoxArchive,
  faArrowTrendUp,
  faSliders,
  faArrowRotateLeft,
  faChevronUp,
};
