/**
 * Mock data for Talent Pool page
 * Contains sample pools and candidate applications
 */

export const POOL_COLORS = [
  { name: 'Gray', value: '#9CA3AF' },
  { name: 'Blue', value: '#3B82F6' },
  { name: 'Indigo', value: '#6366F1' },
  { name: 'Purple', value: '#8B5CF6' },
  { name: 'Pink', value: '#EC4899' },
  { name: 'Red', value: '#EF4444' },
  { name: 'Orange', value: '#F97316' },
  { name: 'Emerald', value: '#10B981' },
  { name: 'Teal', value: '#14B8A6' },
  { name: 'Cyan', value: '#06B6D4' },
];

export const MOCK_CANDIDATES = [
  {
    applicationId: 1001,
    candidateName: 'Nguyen Van A',
    candidateEmail: 'nguyenvana@gmail.com',
    jobTitle: 'Frontend Developer',
    jobId: 1,
    location: 'Ho Chi Minh',
    appliedAt: '2026-04-10T08:30:00',
    resumeUrl: 'https://example.com/cv1.pdf',
    evaluation: { aiScore: 85 },
    status: 'SHORTLISTED',
  },
  {
    applicationId: 1002,
    candidateName: 'Tran Thi B',
    candidateEmail: 'tranthib@gmail.com',
    jobTitle: 'Backend Developer',
    jobId: 2,
    location: 'Ha Noi',
    appliedAt: '2026-04-08T10:15:00',
    resumeUrl: 'https://example.com/cv2.pdf',
    evaluation: { aiScore: 72 },
    status: 'VIEWED',
  },
  {
    applicationId: 1003,
    candidateName: 'Le Hoang C',
    candidateEmail: 'lehoangc@gmail.com',
    jobTitle: 'UI/UX Designer',
    jobId: 3,
    location: 'Da Nang',
    appliedAt: '2026-04-05T14:00:00',
    resumeUrl: null,
    evaluation: { aiScore: 91 },
    status: 'APPROVED',
  },
  {
    applicationId: 1004,
    candidateName: 'Pham Duc D',
    candidateEmail: 'phamducd@gmail.com',
    jobTitle: 'Frontend Developer',
    jobId: 1,
    location: 'Ho Chi Minh',
    appliedAt: '2026-04-12T09:45:00',
    resumeUrl: 'https://example.com/cv4.pdf',
    evaluation: { aiScore: 63 },
    status: 'SHORTLISTED',
  },
  {
    applicationId: 1005,
    candidateName: 'Vo Minh E',
    candidateEmail: 'vominhe@gmail.com',
    jobTitle: 'DevOps Engineer',
    jobId: 4,
    location: 'Ho Chi Minh',
    appliedAt: '2026-04-01T11:30:00',
    resumeUrl: 'https://example.com/cv5.pdf',
    evaluation: { aiScore: 78 },
    status: 'VIEWED',
  },
  {
    applicationId: 1006,
    candidateName: 'Dang Thu F',
    candidateEmail: 'dangthuf@gmail.com',
    jobTitle: 'Backend Developer',
    jobId: 2,
    location: 'Ha Noi',
    appliedAt: '2026-04-09T16:20:00',
    resumeUrl: 'https://example.com/cv6.pdf',
    evaluation: { aiScore: 88 },
    status: 'APPROVED',
  },
  {
    applicationId: 1007,
    candidateName: 'Bui Quang G',
    candidateEmail: 'buiquangg@gmail.com',
    jobTitle: 'Frontend Developer',
    jobId: 1,
    location: 'Da Nang',
    appliedAt: '2026-04-11T08:00:00',
    resumeUrl: null,
    evaluation: { aiScore: 55 },
    status: 'SHORTLISTED',
  },
  {
    applicationId: 1008,
    candidateName: 'Hoang Anh H',
    candidateEmail: 'hoanganhh@gmail.com',
    jobTitle: 'Product Manager',
    jobId: 5,
    location: 'Ho Chi Minh',
    appliedAt: '2026-04-06T13:10:00',
    resumeUrl: 'https://example.com/cv8.pdf',
    evaluation: { aiScore: 95 },
    status: 'APPROVED',
  },
  {
    applicationId: 1009,
    candidateName: 'Nguyen Si Van Hao',
    candidateEmail: 'VH01062023@gmail.com',
    jobTitle: 'Frontend Developer',
    jobId: 1,
    location: 'Metro',
    appliedAt: '2026-04-15T10:00:00',
    resumeUrl: 'https://example.com/cv9.pdf',
    evaluation: { aiScore: 53 },
    status: 'VIEWED',
  },
  {
    applicationId: 1010,
    candidateName: 'Tran Van K',
    candidateEmail: 'tranvank@gmail.com',
    jobTitle: 'UI/UX Designer',
    jobId: 3,
    location: 'Ho Chi Minh',
    appliedAt: '2026-04-13T15:30:00',
    resumeUrl: 'https://example.com/cv10.pdf',
    evaluation: null,
    status: 'APPLIED',
  },
];

export const MOCK_JOBS = [
  { id: 1, name: 'Frontend Developer' },
  { id: 2, name: 'Backend Developer' },
  { id: 3, name: 'UI/UX Designer' },
  { id: 4, name: 'DevOps Engineer' },
  { id: 5, name: 'Product Manager' },
];

export const INITIAL_POOLS = [
  {
    id: 'pool_default',
    name: 'Unassigned',
    color: '#9CA3AF',
    candidateIds: [1001, 1009],
  },
  {
    id: 'pool_frontend',
    name: 'Frontend Potentials',
    color: '#6366F1',
    candidateIds: [1004, 1007],
  },
  {
    id: 'pool_senior',
    name: 'Senior Candidates',
    color: '#10B981',
    candidateIds: [1003, 1006, 1008],
  },
];
